import{S as P,i as j,R as B,A as R}from"./assets/vendor-DZutkQdH.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const i of o)if(i.type==="childList")for(const s of i.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function r(o){const i={};return o.integrity&&(i.integrity=o.integrity),o.referrerPolicy&&(i.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?i.credentials="include":o.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function n(o){if(o.ep)return;o.ep=!0;const i=r(o);fetch(o.href,i)}})();document.addEventListener("DOMContentLoaded",()=>{const e=document.querySelector(".burger-btn"),t=document.querySelector(".mobile-menu"),r=document.querySelector(".mobile-close-btn"),n=document.querySelectorAll(".nav-link, .mobile-nav-link, .btn-buy, .mobile-buy"),o=document.querySelector(".logo"),i=document.querySelector(".furniture-grid");let s=document.querySelector(".loader");s||(s=document.createElement("div"),s.className="loader",s.innerHTML=`<div style="position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);
                          font-size:24px;color:#6b0609;">Завантаження...</div>`,document.body.appendChild(s));const h=()=>s.style.display="block",k=()=>s.style.display="none",v=a=>{iziToast.error({title:"Помилка",message:a,position:"topRight",timeout:3e3})},x=()=>{!t||!e||!r||(t.classList.add("is-open"),t.setAttribute("aria-hidden","false"),document.body.style.overflow="hidden",e.setAttribute("aria-expanded","true"),e.style.display="none",r.style.display="block",r.focus())},f=()=>{!t||!e||!r||(t.classList.remove("is-open"),t.setAttribute("aria-hidden","true"),document.body.style.overflow="",e.setAttribute("aria-expanded","false"),e.style.display="",r.style.display="none",e.focus())};e&&e.addEventListener("click",x),r&&r.addEventListener("click",f),document.addEventListener("keydown",a=>{a.key==="Escape"&&t&&t.classList.contains("is-open")&&f()}),document.addEventListener("click",a=>{t&&t.classList.contains("is-open")&&!t.contains(a.target)&&!e.contains(a.target)&&f()});let w=null;n.forEach(a=>{a.addEventListener("click",async O=>{const b=a.getAttribute("href");if(t&&t.classList.contains("is-open")&&f(),b&&b.startsWith("#")){O.preventDefault();const c=document.querySelector(b);if(c){const p=c.getBoundingClientRect().top+window.pageYOffset+-70;window.scrollTo({top:p,behavior:"smooth"})}}if(b==="#furniture"&&i){h();try{let c;if(w)c=w;else{const l=await fetch("https://furniture-store-v2.b.goit.study/api/furniture");if(!l.ok)throw new Error("Помилка завантаження меблів");c=await l.json(),w=c}i.innerHTML="",c.forEach(l=>{const p=document.createElement("div");p.className="furniture-card",p.innerHTML=`
              <img src="${l.image}" alt="${l.name}">
              <h3>${l.name}</h3>
              <p>${l.description}</p>
            `,i.appendChild(p)})}catch(c){v(c.message)}finally{k()}}})}),o&&o.addEventListener("click",a=>{a.preventDefault(),window.scrollTo({top:0,behavior:"smooth"}),t&&t.classList.contains("is-open")&&f()})});const I="https://furniture-store-v2.b.goit.study/api",_=10,A=()=>document.querySelector(".feedback__loader"),S=()=>document.getElementById("feedbackList"),H=()=>document.querySelector(".feedback__prev"),z=()=>document.querySelector(".feedback__next"),N=()=>{var e;return(e=A())==null?void 0:e.removeAttribute("hidden")};function D(e){const t=Number(e);return t>=3.3&&t<=3.7?3.5:t>=3.8&&t<=4.2?4:Math.round(t*2)/2}function U({name:e,descr:t,rate:r}){return`
    <div class="swiper-slide">
      <article class="feedback-card">
        <div class="feedback-card__content">
          <div class="feedback-card__block">
            <div class="feedback-card__stars" data-score="${D(r)}"></div>
            <p class="feedback-card__text">“${t}”</p>
            <p class="feedback-card__author">${e}</p>
          </div>
        </div>
      </article>
    </div>`}async function V(){var t,r;const e=`${I}/feedbacks?limit=${_}`;try{N();const n=await fetch(e);if(!n.ok)throw new Error(`HTTP ${n.status}`);const o=await n.json();return((t=o==null?void 0:o.feedbacks)==null?void 0:t.slice(0,_))??[]}catch{return j.warning({title:"⚠ API недоступне",message:"Показано тестові дані.",position:"topRight",timeout:2500}),[{name:"Олена Коваль",descr:"Дуже задоволена покупкою! Диван не тільки стильний, а й неймовірно зручний.",rate:4.5},{name:"Ірина Соколова",descr:"Нарешті знайшли меблі, які ідеально вписались у наш інтер’єр.",rate:4},{name:"Андрій Шевченко",descr:"Замовляв шафу й ліжко — все приїхало раніше терміну!",rate:5}]}finally{(r=A())==null||r.remove()}}function Y(){document.querySelectorAll(".feedback-card__stars").forEach(e=>{const t=Number(e.dataset.score||4);new B(e,{readOnly:!0,score:t,half:!0,starType:"img",starOn:"https://cdn.jsdelivr.net/npm/raty-js/lib/images/star-on.png",starOff:"https://cdn.jsdelivr.net/npm/raty-js/lib/images/star-off.png",starHalf:"https://cdn.jsdelivr.net/npm/raty-js/lib/images/star-half.png"}).init()})}function $(e){H().disabled=e.isBeginning,z().disabled=e.isEnd}async function W(){const e=await V();if(!e.length){S().innerHTML=`
      <div class="swiper-slide">
        <p class="feedback-card__text">Немає відгуків 😔</p>
      </div>`;return}S().innerHTML=e.map(U).join(""),Y(),new P(".feedback__swiper",{slidesPerView:3,spaceBetween:24,pagination:{el:".feedback__pagination",clickable:!0},navigation:{prevEl:".feedback__prev",nextEl:".feedback__next"},breakpoints:{320:{slidesPerView:1,spaceBetween:16},768:{slidesPerView:2,spaceBetween:24},1440:{slidesPerView:3,spaceBetween:24}},on:{afterInit(t){$(t)},slideChange(t){$(t)}}})}document.addEventListener("DOMContentLoaded",W);document.addEventListener("DOMContentLoaded",()=>{const e=document.querySelector(".footer-logo"),t=document.querySelectorAll(".footer-link"),r=document.querySelectorAll(".footer-socials a"),n=document.querySelector(".footer-copyright");if(t.forEach(o=>{o.addEventListener("click",i=>{const s=o.getAttribute("href");if(s&&s.startsWith("#")){i.preventDefault();const h=document.querySelector(s);if(h){const v=h.getBoundingClientRect().top+window.pageYOffset+-70;window.scrollTo({top:v,behavior:"smooth"})}}})}),e&&e.addEventListener("click",o=>{window.location.href="./index.html"}),r.forEach(o=>{o.setAttribute("target","_blank"),o.setAttribute("rel","noopener noreferrer")}),n){const o=new Date().getFullYear();n.textContent=`© ${o} Меблерія. Всі права захищені`}});new R(".accordion-container",{duration:500,ariaEnabled:!0,collapse:!0,elementClass:"ac"});const G="https://furniture-store-v2.b.goit.study/api/furnitures",L=document.querySelector(".our-furniture-product-list");let d=1;const m=8,y=document.querySelector(".our-furniture-show-more-btn");async function C(e,t){const r=await fetch(`${G}?page=${e}&limit=${t}`);if(!r.ok)throw new Error("Failed to fetch furniture list");return await r.json()}function T(e){const t=document.createElement("li");return t.className="our-furniture-product-list-card",t.innerHTML=`
        <img src="${e.images[0]}" alt="${e.name}" class="our-furniture-card-image"/>
        <h3 class="our-furniture-card-title">${e.name}</h3>
        <ul class="our-furniture-card-color-list">
            ${e.color.map(r=>`<li class="our-furniture-card-color" style="background-color: ${r};"></li>`).join("")}
          </ul>    
        <p class="our-furniture-card-price">${e.price} грн</p>
        <button class="our-furniture-card-button"data-id="${e._id}">Детальніше</button>
    `,t}function E(){const e=document.querySelector(".loader-wrapper");e&&(e.style.display="flex")}function u(){const e=document.querySelector(".loader-wrapper");e&&(e.style.display="none")}function q(e,t){t.innerHTML="",e.furnitures.forEach(r=>{const n=T(r);t.appendChild(n),e.totalItems>m?J():M()})}function K(){E();try{C(d,m).then(e=>{q(e,L),u()}).catch(e=>{console.error("Error loading furniture list:",e),iziToast.error({title:"Error",message:"Failed to load furniture list. Please try again later."})})}catch(e){console.error("Unexpected error:",e)}}function J(){y.classList.contains("is-open")||y.classList.add("is-open")}function M(){y.classList.contains("is-open")&&y.classList.remove("is-open")}function Q(){d=1}function X(){d+=1,C(d,m).then(e=>{e.furnitures.forEach(t=>{const r=T(t);L.appendChild(r)}),e.totalItems<=d*m&&M()}).catch(e=>{console.error("Error loading more furniture:",e),iziToast.error({title:"Error",message:"Failed to load more furniture. Please try again later."})})}y.addEventListener("click",X);const F="https://furniture-store-v2.b.goit.study/api",g=document.querySelector(".our-furniture-categories");async function Z(){const e=await fetch(`${F}/categories`);if(!e.ok)throw new Error("Failed to fetch furniture categories");return await e.json()}function ee(e){return Array.isArray(e)?e.slice().sort((t,r)=>{const n=t&&t._id?String(t._id):"",o=r&&r._id?String(r._id):"",i=n.slice(-2),s=o.slice(-2);return i.localeCompare(s,void 0,{sensitivity:"base"})}):[]}function te(e){const t=document.createElement("li");return t.innerHTML=`
    <button class="our-furniture-category-card" data-category="${e._id}"> <span class="our-furniture-category-card-label">${e.name}</span>
    </button>
    `,t}function re(e){g.innerHTML='<li><button class="our-furniture-category-card is-active" style="background-image: url(/img/our-furniture/1-x/all-products.jpg); background-image: image-set(url(/img/our-furniture/1-x/all-products.jpg) 1x, url(/img/our-furniture/2-x/all-products@2x.jpg) 2x);"><span class="our-furniture-category-card-label">Всі товари</span></button></li>',e.forEach(t=>{const r=te(t);g.appendChild(r)})}function oe(){E(),Z().then(e=>{re(ee(e)),u()}).catch(e=>{console.error("Error loading furniture categories:",e),iziToast.error({title:"Error",message:"Failed to load furniture categories. Please try again later."}),u()})}async function ne(e,t,r){return await fetch(`${F}/furnitures?page=${e}&limit=${t}`+(r?`&category=${r}`:""))}g.addEventListener("click",e=>{const t=e.target.closest(".our-furniture-category-card");if(!t)return;const r=t.getAttribute("data-category")||null;try{Q(),E(),ne(d,m,r).then(n=>{if(!n.ok)throw new Error("Failed to fetch furniture list by filter");return n.json()}).then(n=>{q(n,L),u()}).catch(n=>{console.error("Error loading filtered furniture list:",n),iziToast.error({title:"Error",message:"Failed to load furniture list. Please try again later."}),u()})}catch(n){console.error("Unexpected error:",n)}});function ie(e){const t=g.querySelector(".our-furniture-category-card.is-active");t&&t.classList.remove("is-active"),e.classList.add("is-active")}g.addEventListener("click",e=>{const t=e.target.closest(".our-furniture-category-card");t&&ie(t)});oe();K();
//# sourceMappingURL=index.js.map
