import{A as a}from"./assets/vendor-BBFahr98.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();document.addEventListener("DOMContentLoaded",()=>{const t=document.querySelector(".footer-logo"),r=document.querySelectorAll(".footer-link"),n=document.querySelectorAll(".footer-socials a"),c=document.querySelector(".footer-copyright");if(r.forEach(e=>{e.addEventListener("click",o=>{const i=e.getAttribute("href");if(i&&i.startsWith("#")){o.preventDefault();const s=document.querySelector(i);if(s){const u=s.getBoundingClientRect().top+window.pageYOffset+-70;window.scrollTo({top:u,behavior:"smooth"})}}})}),t&&t.addEventListener("click",e=>{window.location.href="./index.html"}),n.forEach(e=>{e.setAttribute("target","_blank"),e.setAttribute("rel","noopener noreferrer")}),c){const e=new Date().getFullYear();c.textContent=`© ${e} Меблерія. Всі права захищені`}});new a(".accordion-container",{duration:500,ariaEnabled:!0,collapse:!0,elementClass:"ac"});const l="https://furniture-store-v2.b.goit.study/api/furnitures",d=document.querySelector(".our-furniture-product-list");let f=1;const p=8;async function m(t,r){const n=await fetch(`${l}?page=${t}&limit=${r}`);if(!n.ok)throw new Error("Failed to fetch furniture list");return await n.json()}function h(t){const r=document.createElement("li");return r.className="our-furniture-product-list-card",r.innerHTML=`
        <img src="${t.images[0]}" alt="${t.name}" class="our-furniture-card-image"/>
        <h3 class="our-furniture-card-title">${t.name}</h3>
        <ul class="our-furniture-card-color-list">
            ${t.color.map(n=>`<li class="our-furniture-card-color" style="background-color: ${n};"></li>`).join("")}
          </ul>    
        <p class="our-furniture-card-price">${t.price} грн</p>
        <button class="our-furniture-card-button">Детальніше</button>
    `,r}function g(t,r){r.innerHTML="",t.furnitures.forEach(n=>{const c=h(n);r.appendChild(c)})}function y(){try{m(f,p).then(t=>{g(t,d)}).catch(t=>{console.error("Error loading furniture list:",t),iziToast.error({title:"Error",message:"Failed to load furniture list. Please try again later."})})}catch(t){console.error("Unexpected error:",t)}}y();
//# sourceMappingURL=index.js.map
