import{S as w,i as _,R as S,A}from"./assets/vendor-DZutkQdH.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();document.addEventListener("DOMContentLoaded",()=>{const e=document.querySelector(".burger-btn"),t=document.querySelector(".mobile-menu"),n=document.querySelector(".mobile-close-btn"),i=document.querySelectorAll(".nav-link, .mobile-nav-link, .btn-buy, .mobile-buy"),r=document.querySelector(".logo"),o=document.querySelector(".furniture-grid");let s=document.querySelector(".loader");s||(s=document.createElement("div"),s.className="loader",s.innerHTML=`<div style="position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);
                          font-size:24px;color:#6b0609;">Завантаження...</div>`,document.body.appendChild(s));const f=()=>s.style.display="block",b=()=>s.style.display="none",m=a=>{iziToast.error({title:"Помилка",message:a,position:"topRight",timeout:3e3})},k=()=>{!t||!e||!n||(t.classList.add("is-open"),t.setAttribute("aria-hidden","false"),document.body.style.overflow="hidden",e.setAttribute("aria-expanded","true"),e.style.display="none",n.style.display="block",n.focus())},d=()=>{!t||!e||!n||(t.classList.remove("is-open"),t.setAttribute("aria-hidden","true"),document.body.style.overflow="",e.setAttribute("aria-expanded","false"),e.style.display="",n.style.display="none",e.focus())};e&&e.addEventListener("click",k),n&&n.addEventListener("click",d),document.addEventListener("keydown",a=>{a.key==="Escape"&&t&&t.classList.contains("is-open")&&d()}),document.addEventListener("click",a=>{t&&t.classList.contains("is-open")&&!t.contains(a.target)&&!e.contains(a.target)&&d()});let y=null;i.forEach(a=>{a.addEventListener("click",async E=>{const p=a.getAttribute("href");if(t&&t.classList.contains("is-open")&&d(),p&&p.startsWith("#")){E.preventDefault();const c=document.querySelector(p);if(c){const u=c.getBoundingClientRect().top+window.pageYOffset+-70;window.scrollTo({top:u,behavior:"smooth"})}}if(p==="#furniture"&&o){f();try{let c;if(y)c=y;else{const l=await fetch("https://furniture-store-v2.b.goit.study/api/furniture");if(!l.ok)throw new Error("Помилка завантаження меблів");c=await l.json(),y=c}o.innerHTML="",c.forEach(l=>{const u=document.createElement("div");u.className="furniture-card",u.innerHTML=`
              <img src="${l.image}" alt="${l.name}">
              <h3>${l.name}</h3>
              <p>${l.description}</p>
            `,o.appendChild(u)})}catch(c){m(c.message)}finally{b()}}})}),r&&r.addEventListener("click",a=>{a.preventDefault(),window.scrollTo({top:0,behavior:"smooth"}),t&&t.classList.contains("is-open")&&d()})});const $="https://furniture-store-v2.b.goit.study/api",h=10,L=()=>document.querySelector(".feedback__loader"),g=()=>document.getElementById("feedbackList"),T=()=>document.querySelector(".feedback__prev"),q=()=>document.querySelector(".feedback__next"),O=()=>{var e;return(e=L())==null?void 0:e.removeAttribute("hidden")};function M(e){const t=Number(e);return t>=3.3&&t<=3.7?3.5:t>=3.8&&t<=4.2?4:Math.round(t*2)/2}function x({name:e,descr:t,rate:n}){return`
    <div class="swiper-slide">
      <article class="feedback-card">
        <div class="feedback-card__content">
          <div class="feedback-card__block">
            <div class="feedback-card__stars" data-score="${M(n)}"></div>
            <p class="feedback-card__text">“${t}”</p>
            <p class="feedback-card__author">${e}</p>
          </div>
        </div>
      </article>
    </div>`}async function C(){var t,n;const e=`${$}/feedbacks?limit=${h}`;try{O();const i=await fetch(e);if(!i.ok)throw new Error(`HTTP ${i.status}`);const r=await i.json();return((t=r==null?void 0:r.feedbacks)==null?void 0:t.slice(0,h))??[]}catch{return _.warning({title:"⚠ API недоступне",message:"Показано тестові дані.",position:"topRight",timeout:2500}),[{name:"Олена Коваль",descr:"Дуже задоволена покупкою! Диван не тільки стильний, а й неймовірно зручний.",rate:4.5},{name:"Ірина Соколова",descr:"Нарешті знайшли меблі, які ідеально вписались у наш інтер’єр.",rate:4},{name:"Андрій Шевченко",descr:"Замовляв шафу й ліжко — все приїхало раніше терміну!",rate:5}]}finally{(n=L())==null||n.remove()}}function P(){document.querySelectorAll(".feedback-card__stars").forEach(e=>{const t=Number(e.dataset.score||4);new S(e,{readOnly:!0,score:t,half:!0,starType:"img",starOn:"https://cdn.jsdelivr.net/npm/raty-js/lib/images/star-on.png",starOff:"https://cdn.jsdelivr.net/npm/raty-js/lib/images/star-off.png",starHalf:"https://cdn.jsdelivr.net/npm/raty-js/lib/images/star-half.png"}).init()})}function v(e){T().disabled=e.isBeginning,q().disabled=e.isEnd}async function B(){const e=await C();if(!e.length){g().innerHTML=`
      <div class="swiper-slide">
        <p class="feedback-card__text">Немає відгуків 😔</p>
      </div>`;return}g().innerHTML=e.map(x).join(""),P(),new w(".feedback__swiper",{slidesPerView:3,spaceBetween:24,pagination:{el:".feedback__pagination",clickable:!0},navigation:{prevEl:".feedback__prev",nextEl:".feedback__next"},breakpoints:{320:{slidesPerView:1,spaceBetween:16},768:{slidesPerView:2,spaceBetween:24},1440:{slidesPerView:3,spaceBetween:24}},on:{afterInit(t){v(t)},slideChange(t){v(t)}}})}document.addEventListener("DOMContentLoaded",B);document.addEventListener("DOMContentLoaded",()=>{const e=document.querySelector(".footer-logo"),t=document.querySelectorAll(".footer-link"),n=document.querySelectorAll(".footer-socials a"),i=document.querySelector(".footer-copyright");if(t.forEach(r=>{r.addEventListener("click",o=>{const s=r.getAttribute("href");if(s&&s.startsWith("#")){o.preventDefault();const f=document.querySelector(s);if(f){const m=f.getBoundingClientRect().top+window.pageYOffset+-70;window.scrollTo({top:m,behavior:"smooth"})}}})}),e&&e.addEventListener("click",r=>{window.location.href="./index.html"}),n.forEach(r=>{r.setAttribute("target","_blank"),r.setAttribute("rel","noopener noreferrer")}),i){const r=new Date().getFullYear();i.textContent=`© ${r} Меблерія. Всі права захищені`}});new A(".accordion-container",{duration:500,ariaEnabled:!0,collapse:!0,elementClass:"ac"});const j="https://furniture-store-v2.b.goit.study/api/furnitures",F=document.querySelector(".our-furniture-product-list");let R=1;const N=8;async function H(e,t){const n=await fetch(`${j}?page=${e}&limit=${t}`);if(!n.ok)throw new Error("Failed to fetch furniture list");return await n.json()}function I(e){const t=document.createElement("li");return t.className="our-furniture-product-list-card",t.innerHTML=`
        <img src="${e.images[0]}" alt="${e.name}" class="our-furniture-card-image"/>
        <h3 class="our-furniture-card-title">${e.name}</h3>
        <ul class="our-furniture-card-color-list">
            ${e.color.map(n=>`<li class="our-furniture-card-color" style="background-color: ${n};"></li>`).join("")}
          </ul>    
        <p class="our-furniture-card-price">${e.price} грн</p>
        <button class="our-furniture-card-button">Детальніше</button>
    `,t}function D(e,t){t.innerHTML="",e.furnitures.forEach(n=>{const i=I(n);t.appendChild(i)})}function z(){try{H(R,N).then(e=>{D(e,F)}).catch(e=>{console.error("Error loading furniture list:",e),iziToast.error({title:"Error",message:"Failed to load furniture list. Please try again later."})})}catch(e){console.error("Unexpected error:",e)}}new w(".swiper",{modules:[Navigation,Pagination],navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},pagination:{el:".swiper-pagination",clickable:!0}});z();
//# sourceMappingURL=index.js.map
